from typing import Annotated, Sequence
from datetime import date, timedelta, datetime
from typing_extensions import TypedDict
from langchain_openai import ChatOpenAI
from tradingagents.agents import *
from langgraph.prebuilt import ToolNode
from langgraph.graph import END, StateGraph, START, MessagesState
from langgraph.graph.message import add_messages


# Researcher team state
class InvestDebateState(TypedDict):
    bull_history: Annotated[
        str, "Bullish Conversation history"
    ]  # Bullish Conversation history
    bear_history: Annotated[
        str, "Bearish Conversation history"
    ]  # Bullish Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    current_response: Annotated[str, "Latest response"]  # Last response
    judge_decision: Annotated[str, "Final judge decision"]  # Last response
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


# Risk management team state
class RiskDebateState(TypedDict):
    aggressive_history: Annotated[
        str, "Aggressive Agent's Conversation history"
    ]  # Conversation history
    conservative_history: Annotated[
        str, "Conservative Agent's Conversation history"
    ]  # Conversation history
    neutral_history: Annotated[
        str, "Neutral Agent's Conversation history"
    ]  # Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    latest_speaker: Annotated[str, "Analyst that spoke last"]
    current_aggressive_response: Annotated[
        str, "Latest response by the aggressive analyst"
    ]  # Last response
    current_conservative_response: Annotated[
        str, "Latest response by the conservative analyst"
    ]  # Last response
    current_neutral_response: Annotated[
        str, "Latest response by the neutral analyst"
    ]  # Last response
    judge_decision: Annotated[str, "Judge's decision"]
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


class AgentState(MessagesState):
    company_of_interest: Annotated[str, "Company that we are interested in trading"]
    trade_date: Annotated[str, "What date we are trading at"]

    sender: Annotated[str, "Agent that sent this message"]

    # research step
    market_report: Annotated[str, "Report from the Market Analyst"]
    sentiment_report: Annotated[str, "Report from the Sentiment Analyst"]
    news_report: Annotated[
        str, "Report from the News Researcher of current world affairs"
    ]
    fundamentals_report: Annotated[str, "Report from the Fundamentals Researcher"]
    macro_report: Annotated[str, "Report from the Macro Analyst on macroeconomic conditions"]

    # Bull/Bear structured evaluation output (JSON strings)
    bull_structured_output: Annotated[str, "Bull evaluation JSON (BullBearEvaluation schema)"]
    bear_structured_output: Annotated[str, "Bear evaluation JSON (BullBearEvaluation schema)"]

    # researcher team discussion step (kept for RM judge_decision)
    investment_debate_state: Annotated[
        InvestDebateState, "Current state of the debate on if to invest or not"
    ]
    investment_plan: Annotated[str, "Plan generated by the Analyst"]

    trader_investment_plan: Annotated[str, "Plan generated by the Trader"]

    # risk management team discussion step
    risk_debate_state: Annotated[RiskDebateState, "Current state of the risk management debate"]
    final_trade_decision: Annotated[str, "Final decision made by the Risk Analysts"]

    # position tracking (injected by backtesting engine)
    current_position_pct: Annotated[float, "Current position as % of total capital (0-100)"]
    avg_cost: Annotated[float, "Average cost of current position"]
    total_capital: Annotated[float, "Total account value (cash + position market value)"]
    last_action: Annotated[str, "Last action taken: Buy/Sell/Hold"]
    unrealized_pnl_pct: Annotated[float, "Unrealized PnL as percentage"]

    # regime continuity (injected by backtesting engine)
    prev_regime: Annotated[str, "Previous day market regime (state machine)"]
    regime_entry_reasoning: Annotated[str, "Full reasoning when current regime was first entered"]
    regime_daily_deltas: Annotated[str, "Accumulated daily deltas with regime labels"]

    # per-analyst scoped message channels (isolated from shared `messages`)
    market_messages: Annotated[list, add_messages]
    sentiment_messages: Annotated[list, add_messages]
    news_messages: Annotated[list, add_messages]
    fundamentals_messages: Annotated[list, add_messages]
    macro_messages: Annotated[list, add_messages]

    prev_reasoning: Annotated[str, "Previous day PM reasoning (for PM continuity)"]
    current_price: Annotated[float, "Current close price (injected by engine)"]
